# Pre-commit hooks for NL-FHIR
# Ensures code quality, security, and consistency before commits

repos:
  # Ruff - Fast Python linter and formatter (replaces Black, isort, flake8)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6
    hooks:
      # Run the linter
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      # Run the formatter
      - id: ruff-format

  # Bandit - Security linter
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: [-c, .bandit, -r, src/nl_fhir/]
        pass_filenames: false

  # MyPy - Static type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.1
    hooks:
      - id: mypy
        additional_dependencies: [types-requests, types-PyYAML]
        args: [--ignore-missing-imports, --no-strict-optional]
        files: ^src/

  # Standard pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      # Check for files that would conflict in case-insensitive filesystems
      - id: check-case-conflict
      # Check for merge conflicts
      - id: check-merge-conflict
      # Check YAML syntax
      - id: check-yaml
        args: [--unsafe]  # Allow custom tags in GitHub Actions YAML
      # Check JSON syntax
      - id: check-json
      # Check TOML syntax
      - id: check-toml
      # Ensure files end with newline
      - id: end-of-file-fixer
      # Remove trailing whitespace
      - id: trailing-whitespace
      # Check for large files (> 500KB)
      - id: check-added-large-files
        args: [--maxkb=500]
      # Detect private keys
      - id: detect-private-key
      # Check Python syntax
      - id: check-ast
      # Check for debugger imports
      - id: debug-statements
      # Fix mixed line endings
      - id: mixed-line-ending
        args: [--fix=lf]

  # Safety - Dependency vulnerability scanning
  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.3
    hooks:
      - id: python-safety-dependencies-check
        files: pyproject.toml

  # Prettier - Format YAML, JSON, Markdown
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types_or: [yaml, json, markdown]
        exclude: ^(uv.lock|\.github/workflows/)

# CI configuration - run these in CI with all files
ci:
  autofix_commit_msg: "style: auto-fixes from pre-commit hooks"
  autofix_prs: true
  autoupdate_commit_msg: "chore: update pre-commit hooks"
  skip: [python-safety-dependencies-check]  # Skip slow checks in CI
