version: '3.8'

services:
  # NL-FHIR Application Service
  nl-fhir:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nl-fhir-app
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - LOG_LEVEL=DEBUG
      - CORS_ORIGINS=http://localhost:3000,http://localhost:8080
      - MAX_REQUEST_SIZE_MB=1
      - REQUEST_TIMEOUT_SECONDS=30
      - RATE_LIMIT_REQUESTS_PER_MINUTE=100
    volumes:
      - ./src:/app/src:ro  # Read-only mount for development
      - ./static:/app/static:ro
      - ./templates:/app/templates:ro
    networks:
      - nl-fhir-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; r = requests.get('http://localhost:8000/health'); exit(0 if r.status_code == 200 else 1)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # HAPI FHIR Server for R4 Validation
  hapi-fhir:
    image: hapiproject/hapi:latest
    container_name: nl-fhir-hapi-server
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:testdb
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=null
      - SPRING_DATASOURCE_DRIVERCLASSNAME=org.h2.Driver
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.H2Dialect
      - HAPI_FHIR_VERSION=R4
      - HAPI_FHIR_SERVER_NAME=NL-FHIR Validation Server
      - HAPI_FHIR_CORS_ENABLED=true
      - HAPI_FHIR_CORS_ALLOWED_ORIGINS=http://localhost:8000,http://localhost:3000,http://127.0.0.1:8000
      - HAPI_FHIR_ALLOW_MULTIPLE_DELETE=true
      - HAPI_FHIR_ALLOW_CASCADE_DELETES=true
      - HAPI_FHIR_DEFAULT_ENCODING=json
    networks:
      - nl-fhir-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/fhir/metadata"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    volumes:
      - hapi_data:/tmp/hapi-fhir-jpaserver-starter/target/lucenefiles

  # Future: Redis Cache (Epic 2-3 performance)
  # redis:
  #   image: redis:7-alpine
  #   container_name: nl-fhir-redis
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis-data:/data
  #   networks:
  #     - nl-fhir-network
  #   restart: unless-stopped

networks:
  nl-fhir-network:
    driver: bridge

volumes:
  redis-data:
  hapi_data:
