[project]
name = "nl-fhir"
version = "1.0.0"
description = "Natural Language to FHIR R4 Bundle Converter"
authors = [{name = "NL-FHIR Team"}]
requires-python = ">=3.8"
dependencies = [
    "fastapi>=0.104.1",
    "uvicorn[standard]>=0.24.0", 
    "pydantic>=2.8.0",
    "python-multipart>=0.0.6",
    "jinja2>=3.1.2",
    "pytest>=7.4.3",
    "httpx>=0.25.2",
    "psutil>=5.9.0",  # System monitoring for health checks
    "gunicorn>=20.1.0",  # Production WSGI server
    "python-dotenv>=1.0.0",  # Environment configuration
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/nl_fhir"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]