# Railway.app deployment configuration
# Epic 1 Production Deployment

[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "gunicorn nl_fhir.main:app -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --timeout 120 --access-logfile - --error-logfile -"
healthcheckPath = "/health"
healthcheckTimeout = 10
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

# Environment variables set in Railway dashboard
# - ENVIRONMENT=production
# - LOG_LEVEL=INFO
# - CORS_ORIGINS=$PRODUCTION_FRONTEND_URL
# - ALLOWED_HOSTS=*.up.railway.app
# - SECRET_KEY=$RAILWAY_SECRET_KEY
# - MAX_REQUEST_SIZE_MB=1
# - REQUEST_TIMEOUT_SECONDS=30
# - RATE_LIMIT_REQUESTS_PER_MINUTE=100