"""
TaskResourceFactory - Epic TW-001: Task Workflow Integration
FHIR R4 Task resource factory for clinical workflow management.

Restores Task creation lost when the legacy factory was removed (REFACTOR-008),
so conversion.py can attach workflow Tasks (monitoring, review, assignment,
scheduling) to the bundle.

HIPAA Compliance: Zero PHI in logs, uses patient references only.
"""

import logging
import uuid
from datetime import datetime, timezone
from typing import Any

from .base import BaseResourceFactory

logger = logging.getLogger(__name__)


class TaskResourceFactory(BaseResourceFactory):
    """
    Factory for creating FHIR R4 Task resources.

    Input data keys:
    - status, intent, priority, description (Task fields)
    - patient_id (required): bare id or "Patient/<id>"
    - focus_ref, requester_ref, owner_ref: optional "<Type>/<id>" references
    - code: {"system", "code", "display", "text"}
    - business_status, status_reason (cancelled/failed only), output (completed only)
    """

    DEFAULT_CODE_SYSTEM = "http://hl7.org/fhir/CodeSystem/task-code"

    def __init__(self, validators=None, coders=None, reference_manager=None):
        """Initialize TaskResourceFactory with shared components."""
        super().__init__(validators=validators, coders=coders, reference_manager=reference_manager)
        logger.info("TaskResourceFactory initialized")

    def supports(self, resource_type: str) -> bool:
        """Check if factory supports the resource type."""
        return resource_type == "Task"

    def _add_metadata(self, resource: dict[str, Any], request_id: str | None = None):
        """
        Add FHIR R4-compliant metadata (same approach as ConsentFactory).

        The base class adds non-compliant meta fields ('factory', 'created_at',
        'version') which fail HAPI validation.
        """
        if "meta" not in resource:
            resource["meta"] = {}

        if "tag" not in resource["meta"]:
            resource["meta"]["tag"] = []

        resource["meta"]["tag"].append(
            {
                "system": "http://nl-fhir.io/factory",
                "code": self.__class__.__name__,
                "display": f"Generated by {self.__class__.__name__}",
            }
        )

        if request_id:
            resource["meta"]["tag"].append(
                {"system": "http://nl-fhir.io/request-id", "code": request_id}
            )

        if "id" not in resource or not resource["id"]:
            resource["id"] = str(uuid.uuid4())

    def _create_resource(
        self, resource_type: str, data: dict[str, Any], request_id: str | None = None
    ) -> dict[str, Any]:
        """Create FHIR Task resource."""
        patient_id = data.get("patient_id")
        if not patient_id:
            raise ValueError("patient_id is required for Task")
        if patient_id.startswith("Patient/"):
            patient_id = patient_id[len("Patient/") :]

        status = data.get("status", "requested")
        current_time = datetime.now(timezone.utc).isoformat()

        task: dict[str, Any] = {
            "resourceType": "Task",
            "id": self._generate_resource_id("Task"),
            "status": status,
            "intent": data.get("intent", "order"),
            "description": data.get("description", "Clinical workflow task"),
            "for": {"reference": f"Patient/{patient_id}"},
            "authoredOn": current_time,
            "lastModified": current_time,
        }

        if data.get("priority"):
            task["priority"] = data["priority"]

        if data.get("focus_ref"):
            task["focus"] = {"reference": data["focus_ref"]}

        if data.get("requester_ref"):
            task["requester"] = {"reference": data["requester_ref"]}

        if data.get("owner_ref"):
            task["owner"] = {"reference": data["owner_ref"]}

        code = data.get("code")
        if code:
            task["code"] = {
                "coding": [
                    {
                        "system": code.get("system", self.DEFAULT_CODE_SYSTEM),
                        "code": code.get("code", "fulfill"),
                        "display": code.get("display", "Fulfill the focal request"),
                    }
                ],
                "text": code.get("text", code.get("display", "Clinical workflow task")),
            }

        if data.get("business_status"):
            task["businessStatus"] = {"text": data["business_status"]}

        if data.get("status_reason") and status in ("cancelled", "failed"):
            task["statusReason"] = {"text": data["status_reason"]}

        if data.get("output") and status == "completed":
            task["output"] = [{"type": {"text": "result"}, "valueString": data["output"]}]

        return task
